version: '3.8'

name: 'sasse-estocai'

services:
  db:
    image: postgres:15-alpine
    container_name: estocai-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=estocai
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  db-test:
    image: postgres:15-alpine
    container_name: estocai-db-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=estocai_test
    ports:
      - 5433:5432

volumes:
  postgres-data:
